#!/usr/bin/env python3
"""
douyin-login-auto.py - 抖音自动登录获取 Cookies
使用 Playwright 虚拟浏览器自动打开抖音，扫码登录后保存 Cookies

安装依赖：
    pip3 install playwright
    playwright install chromium

用法：
    python3 douyin-login-auto.py
"""

import json
import os
import sys
import time
from pathlib import Path

# Cookies 保存路径
COOKIES_DIR = Path.home() / ".cookies"
COOKIES_FILE = COOKIES_DIR / "douyin_cookies.txt"
COOKIES_JSON = COOKIES_DIR / "douyin_cookies.json"

def save_cookies_to_netscape(cookies, output_file):
    """将 Cookies 保存为 Netscape 格式"""
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by douyin-login-auto.py\n\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            flag = "TRUE" if domain.startswith('.') else "FALSE"
            path = cookie.get('path', '/')
            secure = "TRUE" if cookie.get('secure') else "FALSE"
            expiry = str(int(cookie.get('expires', 0))) if cookie.get('expires') else "0"
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

def main():
    print("=" * 50)
    print("🤖 抖音自动登录工具")
    print("=" * 50)
    print()
    
    # 检查 playwright
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("❌ Playwright 未安装")
        print()
        print("安装命令：")
        print("  pip3 install playwright")
        print("  playwright install chromium")
        sys.exit(1)
    
    # 创建目录
    COOKIES_DIR.mkdir(parents=True, exist_ok=True)
    
    print("🌐 启动虚拟浏览器...")
    print("   请使用抖音 APP 扫描二维码登录")
    print()
    
    try:
        with sync_playwright() as p:
            # 启动浏览器
            browser = p.chromium.launch(headless=False)
            context = browser.new_context()
            page = context.new_page()
            
            # 访问抖音
            print("📱 打开抖音登录页面...")
            page.goto("https://www.douyin.com")
            
            # 等待登录（扫码或手机号）
            print("⏳ 等待登录...")
            print("   请在浏览器中完成登录操作")
            print()
            
            # 检查是否已登录（通过检查特定元素）
            logged_in = False
            for i in range(60):  # 最多等待 60 秒
                time.sleep(1)
                
                # 检查是否有登录后的特征（如用户头像）
                try:
                    # 抖音登录后的特征元素
                    avatar = page.query_selector('img[class*="avatar"]')
                    if avatar:
                        logged_in = True
                        print("✅ 检测到登录成功！")
                        break
                except:
                    pass
                
                # 显示进度
                if i % 10 == 0:
                    print(f"   等待中... {i}s")
            
            if not logged_in:
                print()
                print("⚠️  未检测到登录状态")
                print("   请确认是否已完成登录")
                input("   按回车键继续...")
            
            # 获取 Cookies
            print()
            print("🍪 获取 Cookies...")
            cookies = context.cookies()
            
            # 保存为 JSON
            with open(COOKIES_JSON, 'w', encoding='utf-8') as f:
                json.dump(cookies, f, ensure_ascii=False, indent=2)
            
            # 保存为 Netscape 格式
            save_cookies_to_netscape(cookies, COOKIES_FILE)
            
            print(f"✅ Cookies 已保存：")
            print(f"   JSON: {COOKIES_JSON}")
            print(f"   Netscape: {COOKIES_FILE}")
            
            # 关闭浏览器
            browser.close()
            
    except Exception as e:
        print(f"❌ 错误：{e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    print()
    print("=" * 50)
    print("✅ 完成")
    print("=" * 50)
    print()
    print("现在可以运行视频总结脚本：")
    print(f"  ~/.openclaw/skills/video-summarizer/scripts/video-summarize.sh \\")
    print(f"      'https://v.douyin.com/xxx'")

if __name__ == "__main__":
    main()
